---
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: {{ .Values.namespace }}
type: Opaque
data:
    token: ZXlKaElqb2lNV1JtTkRabVlXSTFOakZsWmprelptTXpOamMzWkdVNFlXUm1NRGMyTmpVaUxDSjBJam9pTnpSaVltRmpZemt0TUdNMU55MDBNbVk1TFdKaVpHWXRZVE5qWVRJek1Ua3lOemN4SWl3aWN5STZJazR5VG14YVJGRXdUbTFSZEUweVdUQk9lVEF3VGtSck5VeFVhR3BOUjFGMFQxUlpORmt5VFRGT1JFcHJUMFJCTUNKOQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      securityContext:
        sysctls:
        # Allows ICMP traffic (ping, traceroute) to resources behind cloudflared.
          - name: net.ipv4.ping_group_range
            value: "65532 65532"
      containers:
        - image: cloudflare/cloudflared:latest
          name: cloudflared
          env:
            # Defines an environment variable for the tunnel token.
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          command:
            # Configures tunnel run parameters
            - cloudflared
            - tunnel
            - --no-autoupdate
            - --loglevel
            - debug
            - --metrics
            - 0.0.0.0:2000
            - run
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to Cloudflare's network.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
