name: build backend for prd
on:
  repository_dispatch:
    types: [prd]

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-backend.yml
    secrets: inherit
    with:
      environment: prd
      ref: main
      version_tag: ${{ github.event.client_payload.tag }}
