name: build backend for dev
on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-backend.yml
    secrets: inherit
    with:
      environment: dev
      ref: development
      version_tag: development
