name: build chrome extension for prd
on:
  repository_dispatch:
    types: [prd]

jobs:
  build-and-publish:
    uses: ./.github/workflows/_build-ext.yml
    secrets: inherit
    with:
      environment: prd
      ref: main
      extension_id: dfkedikhakpapbfcnbpmfhpklndgiaog
