name: build chrome extension for stg
on:
  repository_dispatch:
    types: [stg]

jobs:
  build-and-publish:
    uses: ./.github/workflows/_build-ext.yml
    secrets: inherit
    with:
      environment: stg
      ref: staging
      extension_id: gjkgbnnlfophcfffoinfgdnhjnfankbn
