name: build backend for stg
on:
  repository_dispatch:
    types: [stg]

jobs:
  build-and-deploy:
    uses: ./.github/workflows/_build-backend.yml
    secrets: inherit
    with:
      environment: stg
      ref: staging
      version_tag: ${{ github.event.client_payload.tag }}
